# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 530)
        MainWindow.setStyleSheet("background-color: rgb(101, 255, 90);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(171, 245, 158);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_addition1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addition1.setGeometry(QtCore.QRect(90, 255, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_addition1.setFont(font)
        self.btn_addition1.setStyleSheet("background-color: rgb(228, 231, 244);")
        self.btn_addition1.setObjectName("btn_addition1")
        self.btn_subtraction1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subtraction1.setGeometry(QtCore.QRect(410, 255, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_subtraction1.setFont(font)
        self.btn_subtraction1.setStyleSheet("background-color: rgb(228, 231, 244);")
        self.btn_subtraction1.setObjectName("btn_subtraction1")
        self.fl_title1 = QtWidgets.QLabel(self.centralwidget)
        self.fl_title1.setGeometry(QtCore.QRect(200, 100, 301, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fl_title1.setFont(font)
        self.fl_title1.setObjectName("fl_title1")
        self.btn_exit1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit1.setGeometry(QtCore.QRect(280, 425, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit1.setFont(font)
        self.btn_exit1.setStyleSheet("background-color: rgb(228, 231, 244);")
        self.btn_exit1.setObjectName("btn_exit1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тренажер"))
        self.btn_addition1.setText(_translate("MainWindow", "Сложение"))
        self.btn_subtraction1.setText(_translate("MainWindow", "Вычитание"))
        self.fl_title1.setText(_translate("MainWindow", "Выберите тренажер"))
        self.btn_exit1.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
